### ISSUE TITLE
invalid Token

### ISSUE THREAD

**Issue by tommyfinn** [eracknaphobia/plugin.video.psvue#1]
I have an account. Able to login online and watch live online. tryed clearing cache and deleting userdata folder

**Comment by justinro** [comment]
Same here - Looks like PSVue changed their login auth process

**Comment by rickromkey** [comment]
Same issue here....help!

**Comment by htpcforall** [comment]
I kind of jump started it by manually inserting auth data (i.e. cookies) previously captured from my browser session. Not practical for 99% but it does work.

**Comment by tommyfinn** [comment]
@htpcforall could you point me to a guide or something on how to do i would like to give it a try

**Comment by eracknaphobia** [comment]
After a long weekend of trial and error, I've finally found a fix for the login issue. I just need to test it for a few more days to make sure it's stable.

**Comment by lsawyer3** [comment]
A few days... any way we could have a beta version to test with you?

**Comment by eracknaphobia** [comment]
Fix released, please test and let me know.

**Comment by tommyfinn** [comment]
@eracknaphobia i'm getting Authorization Failed: Could not retrieve the reqpayload. I will try on anther device

**Comment by tommyfinn** [comment]
Worked

**Comment by RedManMark86** [comment]
I'm getting a
"could not retrieve the reqpayload" error

**Comment by tommyfinn** [comment]
having to click on some channels multiple times before they start.

**Comment by eracknaphobia** [comment]
I'm closing this issue as it is getting off topic of the original issue. Please post new issues separately.

**Comment by htpcforall** [comment]
Tommy. Are you still having trouble?
