### ISSUE TITLE
Have to click multiple times on live channel in order to play

### ISSUE THREAD

**Issue by justinro** [eracknaphobia/plugin.video.psvue#2]
Also having an issue where channels in the Live-TV section just go to a black screen initially, and I have to click on them 5 or 6 times for it to work:

https://pastebin.com/raw/MEKZxcRg

**Comment by eracknaphobia** [comment]
Try updating your kodi version to the latest stable version, currently Krypton 17.4.

**Comment by justinro** [comment]
Any way this can be tweaked to work with Jarvis? There are some bugs in Krypton that haven't been fixed yet, so I'm holding off on updating, but would love to have a working Vue plugin in the meantime. Of course, no worries if it would be too time consuming..Cheers!

**Comment by eracknaphobia** [comment]
Not that I'm aware of, maybe try a nightly (Leia 18).

**Comment by justinro** [comment]
Tried out Leia, and the plugin does work better - The streams do play eventually, but there's a good 6-7 second delay from selecting a channel and it actually playing. Is that to be expected?

**Comment by eracknaphobia** [comment]
By default yes. Try enabling input stream adaptive (Addons > My Addons > Video inputstream). It’s a bit buggy in 17.4, but the nightly should have the latest and greatest. Streams should start much quicker.

**Comment by DiR3Wolf** [comment]
This problem, about stream feed being stopped and not able to resume while input stream is enabled, still persist in Leia. Is this bug an issue with inputstream alone, or is it a compatibility issue between inputstream and PSVue? If the former, are they aware of the issue and how in impacts PSVue? thanks!!!!

**Comment by eracknaphobia** [comment]
As far as I know, it's an inputstream issue.  The streams seem to work fine every time with inputstream turned off.

**Comment by DiR3Wolf** [comment]
Yes, they work well with inputstream off(not perfect, I still encounter few disconnection issues and sounds issues that stop/play fixes). I was wondering if there was some compatibility issues between both addons, that may not necessarily be a bug.

If this is a bug, is the bug acknowledge by the input stream developer?

Can't thank you enough for this PSVue addon. It makes Kodi becoming a single TV interface closer to reality.

**Comment by snoopyjoe** [comment]
Yeah something really funky is happening with inputstream. I've noticed that streams like ESPN which may only a display a "Commercial break in progress" screensaver during commercials will crash Videoplayer when the stream switches to a commercial. Disabling inputstream fixes the issue but there can be a bit of stutter and audio problems with it disabled. I don't follow the developer for inputstream but it doesn't hurt to see if it's an issue on their github.
