### ISSUE TITLE
Improve Movie Section

### ISSUE THREAD

**Issue by eracknaphobia** [eracknaphobia/plugin.video.psvue#30]
I like the movie section, but it was pretty slow to load and it cut off arbitrarily at 600. I've add functionality to let user "page" through 40 movies at a time. Right now it's just all movies sorted by most popular.

I'd like to add the ability to: 
 - switch the genre (popular, action, comedy, scifi) 
 - sort (alphabetic, popular) 

https://github.com/eracknaphobia/plugin.video.psvue/blob/fca70134339f2d20936e8062ed67e0058a46600e/resources/lib/ps_vue.py#L83-L98

**Comment by snoopyjoe** [comment]
I was talking in the forum with someone else about this. The app has a dozen genres to choose from but the website only has four. It shouldn't be hard to add the sorting but the "All" subtype probably should probably be depreciated. 

Would it be better to and choice menu like that of "Next Airings" and have the choose the genre or make each genre a directory? Just trying to see which would be less code.

**Comment by eracknaphobia** [comment]
Actually it wasn't too bad to code, figuring out the genre codes was the hard part 😉 
I took the dialog approach less clutter on the screen the better.

https://github.com/eracknaphobia/plugin.video.psvue/blob/dc7f311a7dcc519e91793f7eb53f92fc775d670f/resources/lib/ps_vue.py#L573-L641

**Comment by snoopyjoe** [comment]
Wow! I don't know how you found all the sub types besides randomly typing in a number and hoping it returns a json lol. This is great though, nice work!

**Comment by snoopyjoe** [comment]
I modified the navigation of the movie section a bit. Before, the genre selection was a directory in the movie section. So opening the movie section loaded the movies and the next and genre selection directories. Now clicking on the movie section opens the genre dialog first then loads the selected movies. Other than that it works great. Nice stuff again.
[Main.py](https://github.com/snoopyjoe/plugin.video.psvue/blob/6e19d7b54075abcff48442ed96179bc6a2a82647/main.py#L91-L96)
[PSvue.py](https://github.com/snoopyjoe/plugin.video.psvue/blob/1261ae401e84226fde390c2f2d91568348e11f8c/resources/lib/ps_vue.py#L83-L93)
