### ISSUE TITLE
channels turn off

### ISSUE THREAD

**Issue by tommyfinn** [eracknaphobia/plugin.video.psvue#4]
randomly while viewing a channel, it stops and goes back to the channel list screen

**Comment by eracknaphobia** [comment]
This may be caused by a bug in inputstream adaptive. Check if you have it enabled and disabled it. You can find it here: 
Addons > My Addons > VideoPlayer Inputstream > Inputstream Adaptive

**Comment by tommyfinn** [comment]
It works better, but still disconnects.

**Comment by DiR3Wolf** [comment]
@eracknaphobia I believe all this issues have been resolved of last release (or at least a workaround implemented), correct? I think for issues #2, #4, and I believe #3 has also been resolved.

If you agree, could you close all these issues to keep the repo friendly to more relevant issues? Thanks!!!

**Comment by eracknaphobia** [comment]
This issue is fairly old and the updates should have fixed this issue. If you are still experiencing problems please start a new issue.
